"""Pydantic contracts and schemas for H.A.T.S AI Copilot."""

from __future__ import annotations

import datetime as dt
from typing import Any, List, Optional
from pydantic import BaseModel, Field


class Citation(BaseModel):
    """Citation linking back to a retrieved document or tool result."""
    source_id: str = Field(..., description="Unique source or tool identifier")
    title: str = Field(..., description="Title of the source or tool call")
    url_or_path: str = Field(..., description="File path or documentation link")
    snippet: str = Field(..., description="Excerpt or summarized proof from the source")


class TradeIdea(BaseModel):
    """Structured trade idea generated by the Quant Analyst agent."""
    action: str = Field(..., description="Trade action: 'BUY', 'SELL', 'HOLD', 'EXIT'")
    symbol: str = Field(..., description="Target ticker symbol (e.g. 'SPY', 'AAPL')")
    strategy: str = Field(..., description="Quantitative strategy model used")
    suggested_entry: Optional[float] = Field(None, description="Suggested entry price")
    stop_loss: Optional[float] = Field(None, description="Stop loss price level")
    take_profit: Optional[float] = Field(None, description="Take profit target price")
    position_size_pct: float = Field(0.05, description="Suggested allocation as % of equity")
    rationale: str = Field(..., description="Quantitative rationale for the trade setup")


class RiskAssessment(BaseModel):
    """Deterministic risk evaluation produced by the Risk Agent."""
    risk_compliant: bool = Field(..., description="True if position satisfies all risk limits")
    stress_drawdown_pct: float = Field(..., description="Max predicted drawdown from 15-scenario stress grid")
    circuit_breaker_passed: bool = Field(..., description="Whether circuit breaker is normal/active")
    circuit_breaker_state: str = Field("NORMAL", description="NORMAL, CAUTION, or HALTED")
    short_option_margin_floor_applied: bool = Field(False, description="Whether short option risk floor was enforced")
    violations: List[str] = Field(default_factory=list, description="List of risk violation reasons if any")


class BacktestMetricReport(BaseModel):
    """Deterministic backtest results produced by the backtest tool."""
    strategy: str
    symbol: str
    cagr_pct: float
    sharpe_ratio: float
    max_drawdown_pct: float
    win_rate_pct: float
    total_trades: int


class ResearchReport(BaseModel):
    """Final grounded research output delivered to the user."""
    query: str = Field(..., description="Original user prompt")
    summary: str = Field(..., description="Executive summary of the research")
    market_regime: str = Field("UNKNOWN", description="Current detected market regime (Trending/Mean-Reverting)")
    hurst_exponent: Optional[float] = Field(None, description="Calculated Hurst exponent for regime")
    trade_ideas: List[TradeIdea] = Field(default_factory=list, description="Proposed trade setups")
    risk_assessment: RiskAssessment = Field(..., description="Verified risk engine stress test results")
    backtest_benchmarks: List[BacktestMetricReport] = Field(default_factory=list, description="Historical performance results")
    citations: List[Citation] = Field(default_factory=list, description="Verified references and tool sources")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Overall groundedness confidence score (0.0 to 1.0)")
    critic_notes: Optional[str] = Field(None, description="Notes or critiques from the Critic Agent")
    timestamp: str = Field(default_factory=lambda: dt.datetime.now(dt.timezone.utc).isoformat())


class ResearchQueryRequest(BaseModel):
    """API request payload for research questions."""
    query: str
    session_id: Optional[str] = None
    stream: bool = False
    symbols: Optional[List[str]] = None


class UserFeedbackRequest(BaseModel):
    """User feedback on an AI research report."""
    query_id: str
    rating: int = Field(..., ge=1, le=5, description="1 to 5 star rating")
    is_positive: bool = Field(True, description="Thumbs up / down flag")
    feedback_text: Optional[str] = None
    corrections: Optional[str] = None
